name: Daily Job

on:
  schedule:
    - cron: '0 12 * * *'  # This will run the action once a day
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: |
        python main.py
      env:
        RESEND_KEY: ${{ secrets.RESEND_KEY }}
